[[redirects]]
  from = "/api/*"
  to = "https://shopit-app-jp36.onrender.com/:splat"
  status = 200

[build]
command = "npm run build"  # Replace with your build command
publish = "frontend/build"         # Replace with your build output directory (e.g., "dist", "public")
